import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Available.module.css'
import Link from 'next/link'
import React from 'react'

export default function available() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fuel Quentity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tabb.ico" />
      </Head>

      <main>
      <div className={styles.sidenav}>
      <ul>
          <li><a href="">&#9776;</a></li>
          <li><a href="/">Home</a></li>
          <li><a href="/profile">Profile-Overveiw</a></li>
          <li><a href="">Your-Earning</a></li>
          <li><a href="/available">Fuel-Quantity</a></li>
          <li><a href="">Notification</a></li>
          <li><a href="">Settings</a></li>
          <li><a href="/signin">Login</a></li></ul>
          <br></br><br></br><br></br><br></br>
          <li><a href="/"><Image src='/logo.png' width={50} height={50}/></a></li>
        </div>
        
        <div className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Urban Tour
        </h1>
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Morotuwa IOC Filling station</h2>
            <p className={styles.loopp}>Available Fuel Types</p>
            <div>
            <ul>
              <li><button>P92</button></li>
              <li><button>&#9981;</button></li>
              <li><button>P95</button></li>
              <li><button>&#9981;</button></li>
              <li><button>D</button></li>
              <li><button>&#9981;</button></li>
              <li><button>SD</button></li>
              <li><button>&#9981;</button></li>
            </ul>   
            </div>
              <hr/>
            
            <p className={styles.loopp}>Fuel volume for the day <br></br>2022/08/03</p>

            <div>
              <label>&#x26FD; Petrol-92 :</label>
              <a className={styles.barr}>&#x1F704; 4000L</a> <br></br>
              <progress value="90" max="100"> 90%</progress><br></br>

              <label>&#x26FD; Petrol-95 :</label>
              <a  className={styles.barr}>&#x1F704; 2500L</a><br></br>
              <progress  value="50" max="100"> 50%</progress><br></br>
              <label>&#x26FD; Diesel :</label>
              <a  className={styles.barr}>&#x1F704; 9000L</a><br></br>
              <progress  value="20" max="100"> 20%</progress><br></br>
              <label>&#x26FD; Super-Diesel :</label>
              <a  className={styles.barr}>&#x1F704; 2547L</a><br></br>
              <progress value="80" max="100"> 80%</progress><br></br>
            </div>
            <hr/>
            <button type="button" className="btn btn-outline-primary"><b>BOOK-TIME-SLOT</b></button>

          </a> 
        </div>
        </div>
      </main>

      

    </div>
  )
}
