import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React from 'react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Urban Tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Urban Tour
        </h1>



        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Morotuwa IOC Filling station</h2>
            <p className={styles.loopp}>Available Fuel Types</p>
            <div>
            <ul>
              <li><button>P92</button></li>
              <li><button>P95</button></li>
              <li><button>D</button></li>
              <li><button>SD</button></li>
            </ul>   
            </div>
              <hr/>
            
            <p className={styles.loopp}>Fuel volume for the day <br></br>2022/08/03</p>

            <div>
              <label>Petrol-92 :</label>
              <a className={styles.barr}> 250L</a> <br></br>
              <progress  value="25" max="100"> 25%</progress><br></br>

              <label>Petrol-95 :</label>
              <a  className={styles.barr}> 250L</a><br></br>
              <progress  value="50" max="100"> 50%</progress><br></br>
              <label>Diesel :</label>
              <a  className={styles.barr}> 250L</a><br></br>
              <progress  value="75" max="100"> 75%</progress><br></br>
              <label>Super-Diesel :</label>
              <a  className={styles.barr}> 250L</a><br></br>
              <progress value="80" max="100"> 80%</progress><br></br>
            </div>
            <hr/>
          <button className={styles.hjk}>Book Time Slot!</button>

          </a> 
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Copyright ©️ 2022. All rights reserved.
                        Designed & developed by GROUP-16
        </a>
      </footer>

    </div>
  )
}
