import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React from 'react'

export default function hj() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Urban Tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Link href="/fuel"><a><u>fuel</u></a></Link>

      </main>

      <footer className={styles.footer}>
        <a>
          Copyright ©️ 2022. All rights reserved.
                        Designed & developed by GROUP-16
        </a>
      </footer>

    </div>
  )
}
