import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React from 'react'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Urban Tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
          

          <a className={styles.card}>
            <h2><u>PROFILE</u> </h2><br></br>

            <p>
            <div className='tab-pane fade show active' id="home" role="tabpanel"aria-labelledby="home-tab">
                            
                            <div className="row">
                                <div className="col-md-4">
           <label> <img src='/Boyim.png' width={200} height={200} alt="error" /></label>
           </div>
           <div className="col-md-4">
                <h5>Promoda Hasan</h5>
                <br></br>
                
                <input type="submit" name='btnAddmore' value="Edit Profile"  class="btn btn-primary btn-mid" />
             </div>
             </div>

             </div>
         

           

            <div >
             
              
            </div>
            


            <div >
             
                
               <hr/>
               
                <div >
                    <div >
                        <div className='tab-pane fade show active' id="home" role="tabpanel"aria-labelledby="home-tab">
                            
                            <div className="row">
                                <div className="col-md-3">
                                    <label><b>USER-ID : </b></label>
                                </div>
                                <div className="col-md-3">
                                    <p className={styles.lol}>543543535</p>
                                </div>
                            </div> 
                            <div className="row mt-3">
                                <div className="col-md-3">
                                    <label><b>NAME : </b></label>
                                </div>
                                <div className="col-md-3">
                                    <p className={styles.lol}>Rohan </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-3">
                                    <label><b>AGE : </b></label>
                                </div>
                                <div className="col-md-5">
                                    <p className={styles.lol}>23 </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-3">
                                    <label><b>NUMBER : </b></label>
                                </div>
                                <div className="col-md-5">
                                    <p className={styles.lol}>0761234565 </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-3">
                                    <label><b>EMAIL : </b></label>
                                </div>
                                <div className="col-md-3">
                                    <p className={styles.lol}>Rohan123@gmail.com </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-3">
                                    <label><b>ADRESS : </b></label>
                                </div>
                                <div className="col-md-5">
                                    <p className={styles.lol}>53/A11, Meepe Road, Padukka </p>
                                </div>
                            </div>
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>

             <hr/>
             <p className={styles.loll}>Prograss Bar</p>
            <div>
            <div clas s="page-content page-container" id="page-content">
    <div className={styles.padding}>
        <div class="row container d-flex justify-content-center">
        
        <div class="col-xl-12">
                                                <div class="card proj-progress-card">
                                                    <div className={styles.cardblock}>
                                                        <div class="row">
                                                            <div class="col-xl-3 col-md-6">
                                                                <h6> Distance </h6>
                                                                <h5 class="m-b-30 f-w-700">5<span className={styles.textcgreen}> Km</span></h5>
                                                                <progress id="file" value="20" max="100"> 20% </progress>
                                                               
                                                            </div>
                                                            <div class="col-xl-3 col-md-6">
                                                                <h6>  Speed  </h6>
                                                                <h5 class="m-b-30 f-w-700">4<span className={styles.textcred}>Km/h</span></h5>
                                                                <progress id="file" value="25" max="100"> 25% </progress>
                                                            </div>
                                                            <div class="col-xl-3 col-md-6">
                                                                <h6> Calories </h6>
                                                                <h5 class="m-b-30 f-w-700">89<span className={styles.textcgreen}>Cal</span></h5>
                                                                <progress id="file" value="10" max="100"> 10% </progress>
                                                            </div>
                                                            <div class="col-xl-3 col-md-6">
                                                                <h6> Duration </h6>
                                                                <h5 class="m-b-30 f-w-700">36<span className={styles.textcred}>H</span></h5>
                                                                <progress id="file" value="18" max="100"> 18% </progress>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
        
        
        
        </div>
    </div>
</div>
        
        

        </div>






            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Copyright ©️ 2022. All rights reserved.
                        Designed & developed by GROUP-16
        </a>
      </footer>

    </div>
  )
}
