import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Profile.module.css'
import Link from 'next/link'
import React from 'react'


export default function profile() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile Overveiw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tabb.ico" />
      </Head>

      <main>
      <div className={styles.sidenav}>
      <ul>
          <li><a href="">&#9776;</a></li>
          <li><a href="/">Home</a></li>
          <li><a href="/profile">Profile-Overveiw</a></li>
          <li><a href="">Your-Earning</a></li>
          <li><a href="/available">Fuel-Quantity</a></li>
          <li><a href="">Notification</a></li>
          <li><a href="">Settings</a></li>
          <li><a href="/signin">Login</a></li></ul>
          <br></br><br></br><br></br><br></br>
          <li><a href="/"><Image src='/logo.png' width={50} height={50}/></a></li>
        </div>
        
        <div className={styles.main}>

        <div className={styles.grid}>
          

          <a className={styles.card}>
            <h2><u>PROFILE-OVERVEIW</u> </h2><br></br>

            <p>
            <div className='tab-pane fade show active' id="home" role="tabpanel"aria-labelledby="home-tab">
                            
                            <div className="row">
                                <div className="col-md-6">
           <label> <img src='/Boyim.png' width={200} height={200} alt="error" /></label>
           </div>
           <div className="col-md-2">
                <h5>Promoda Hasan</h5>
                
                
                <input type="submit" name='btnAddmore' value="Edit Profile"  classname="btn btn-primary btn-mid" />
             </div>
             </div>

             </div>
         

           

            <div >
             
              
            </div>
            


            <div >
             
                
               <hr/>
               
                <div >
                    <div >
                        <div className='tab-pane fade show active' id="home" role="tabpanel"aria-labelledby="home-tab">
                            
                            <div className="row">
                                <div className="col-md-4">
                                    <label><b>USER-ID : </b></label>
                                </div>
                                <div className="col-md-3">
                                    <p className={styles.lol}>543543535</p>
                                </div>
                            </div> 
                            <div className="row mt-3">
                                <div className="col-md-4">
                                    <label><b>NAME : </b></label>
                                </div>
                                <div className="col-md-3">
                                    <p className={styles.lol}>Rohan </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-4">
                                    <label><b>AGE : </b></label>
                                </div>
                                <div className="col-md-5">
                                    <p className={styles.lol}>23 </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-4">
                                    <label><b>NUMBER : </b></label>
                                </div>
                                <div className="col-md-5">
                                    <p className={styles.lol}>0761234565 </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-4">
                                    <label><b>EMAIL : </b></label>
                                </div>
                                <div className="col-md-3">
                                    <p className={styles.lol}>Rohan123@gmail.com </p>
                                </div>
                            </div>
                            <div className="row mt-3">
                                <div className="col-md-4">
                                    <label><b>ADRESS : </b></label>
                                </div>
                                <div className="col-md-7">
                                    <p className={styles.lol}>53/A11, Meepe Road, Padukka. </p>
                                </div>
                            </div>
                            
                            
                                    
                                </div>
                            </div>
                        </div>
                    </div>

             
                    

            </p>
          </a>
        </div>
        <footer className={styles.footer}>
       
        <a>
          Copyright © 2022. All rights reserved.
                        Designed & developed by GROUP-16
        </a>
      </footer>
        </div>
      </main>

      <div className={styles.grid}>
          <a className={styles.card}>
            <h2><u>WEEKLY-REPORT</u> <br></br><k>Promoda Hasan</k></h2>
            <p>
             <hr/>
           
            <div>
            <div className="page-content page-container" id="page-content">
    <div className={styles.padding}>
        <div classname="row container d-flex justify-content-center">
        
        <div classname="col-xl-8">
                                                <div classname="card proj-progress-card">
                                                    <div className={styles.cardblock}>
                                                        <div classname="row">
                                                            <div classname="col-xl-3 col-md-6">
                                                                <h6 className={styles.lolll}> DISTANCE </h6>
                                                                <h5 classname="m-b-30 f-w-700">7<span className={styles.textcgreen}> &#x1F6B2; KM</span></h5>
                                                                <progress  value="70" max="100"> 70% </progress>
                                                            </div><br></br>
                                                            <div classname="col-xl-3 col-md-6">
                                                                <h6 className={styles.lolll}>  SPEED </h6>
                                                                <h5 classname="m-b-30 f-w-700">4<span className={styles.textcred}> &#x1F6B4; KM/H</span></h5>
                                                                <progress  value="25" max="100"> 25% </progress>
                                                            </div><br></br>
                                                            <div classname="col-xl-3 col-md-6">
                                                                <h6 className={styles.lolll}> CALORIES </h6>
                                                                <h5 classname="m-b-30 f-w-700">5412<span className={styles.textcgreen}> &#128293; Cal   </span></h5>
                                                                <progress  value="55" max="100"> 55% </progress>
                                                            </div><br></br>
                                                            <div classname="col-xl-3 col-md-6">
                                                                <h6 className={styles.lolll}> SPEND-TIME </h6>
                                                                <h5 className="m-b-30 f-w-700">36:45:05<span className={styles.textcred}>  &#9201;  HH:MM:SS</span></h5>
                                                                <progress  value="60" max="100"> 60% </progress>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
        
        
                        
                        </div>
                    </div>
                </div>
                        
        

            </div>

            </p>
          </a>
        </div>
       
    </div>
  )
}
