import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Reg.module.css'
import { Formik, Field, Form } from 'formik';
import React from 'react'
import Link from 'next/link'
  
export default function reg() {
    return (
        <div className={styles.container}>
        <Head>
          <title>Urban Tour Reg</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/tabb.ico" />
        </Head>
  
        <main className={styles.main}>
          <h4 className={styles.title}>
            Welcome to Urban-Tour Registration.
          </h4>
          <div className={styles.grid}>
                    <a className={styles.card}>
                      <h2><b>In order to create an Urban Tour account, please fill out this form.</b></h2>
                      <p>
                    <Formik
                      initialValues={{
                          username: '',
                          password: '',
                      }}
  
                      onSubmit={() => {
  
                      }}
                    >
                      <Form>
                          <label>Email</label>
                          <input type="text" id="Email" name="email"  /><br></br>
                          <label >Fullname</label>
                          <input type="text" id="username" name="username"  /><br></br>
                          <label >phone-number</label>
                          <input type="text" id="username" name="username"  /><br></br>
                          <label >Password</label>
                          <input type="password"  id="password" name="password"  /><br></br>
                          <label >Re-Enter-Password</label>
                          <input type="password" id="repassword" name="repassword"  /><br></br>
                          <button type="submit">Sign-up</button>
                      </Form>
                      </Formik>
                      ** By creating an account you agree to our <u>Terms & Privacy.</u><br></br>
                      ** Need To <Link href="/signin" ><a><u> SIGN-IN </u>&#10237;</a></Link>
                       </p>
                    </a>
                 
          </div>
          <footer className={styles.footer}>
        <a>
          Copyright © 2022. All rights reserved.
                        Designed & developed by GROUP-16
        </a>
      </footer>
        </main>
      </div>
    )
  }
  