import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Formik, Field, Form } from 'formik';
import React from 'react'
  
export default function reg() {
    return (
        <div className={styles.container}>
        <Head>
          <title>Urban Tour</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/tabb.ico" />
        </Head>
  
        <main className={styles.main}>
          <h4 className={styles.title}>
            Welcome to Urban-Tour
          </h4>
  
          <p className={styles.description}>
           
          </p>
  
          <div className={styles.grid}>
                    <a className={styles.card}>
                      <h2>Please fill in this form to create an account.</h2>
                      <p>
                    <Formik
                      initialValues={{
                          username: '',
                          password: '',
                      }}
  
                      onSubmit={() => {
  
                      }}
                    >
                      <Form>
                          <label>Email</label>
                          <input type="text" id="Email" name="email"  /><br></br>
                          <label >Fullname</label>
                          <input type="text" id="username" name="username"  /><br></br>
                          <label >phone-number</label>
                          <input type="text" id="username" name="username"  /><br></br>
                          <label >Password</label>
                          <input type="password"  id="password" name="password"  /><br></br>
                          <label >Re-Enter-Password</label>
                          <input type="password" id="repassword" name="repassword"  /><br></br>
                          ** By creating an account you agree to our <u>Terms & Privacy.</u>
                          <button type="submit">Sign-up</button>
                      </Form>
                      </Formik>
                
                       </p>
                    </a>
                 
          </div>
        </main>
  
        <footer className={styles.footer}>
          <a>
            Copyright © 2022. All rights reserved.
                          Designed & developed by GROUP-16
          </a>
        </footer>
      </div>
    )
  }
  