import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Signin.module.css'
import { Formik, Field, Form } from 'formik';
import Link from 'next/link'
import React from 'react'

export default function signin() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign-in page</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/tabb.ico" />
      </Head>

      <main>
      <div className={styles.sidenav}>
      <ul>
          <li><a href="">&#9776;</a></li>
          <li><a href="/">Home</a></li>
          <li><a href="/profile">Profile-Overveiw</a></li>
          <li><a href="">Your-Earning</a></li>
          <li><a href="/available">Fuel-Quantity</a></li>
          <li><a href="">Notification</a></li>
          <li><a href="">Settings</a></li>
          <li><a href="/signin">Login</a></li></ul>
          <br></br><br></br><br></br><br></br><br></br>
          <li><a href="/"><Image src='/logo.png' width={50} height={50}/></a></li>
        </div>
        
        <div className={styles.main}>
        <h2 className={styles.title}>
          Welcome to Urban-Tour
        </h2>
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Sign-in</h2>
            
            <p> 
            <Formik
            initialValues={{
                username: '',
                password: '',
            }}

            onSubmit={() => {

            }}
           >
            <Form>
                <label >Email</label>
                <input type="text" id="username" name="username"/><br></br>
                <label >Password</label>
                <input type="password" id="password" name="password" /><br></br>
                <button type="submit">Sign-in</button>
                <u><a href="#">Forgot password?</a></u>
            </Form>
            
        </Formik><br></br>

        ** Need an account?? <Link href="/reg"><a><u>SIGN-UP</u>&#9660;</a></Link>
        </p>
          </a> 

        </div>
        <footer className={styles.footer}>
        <a>
          Copyright © 2022. All rights reserved.
                        Designed & developed by GROUP-16
        </a>
      </footer>
      </div>
      </main>

      
    </div>
  )
}
